development:
  url: sqlite://a/b

sqlite:
  url: sqlite://a/b

postgres:
  url: postgres://postgres:rahasia@localhost:5432/kratos-test?sslmode=disable&max_conns=20&max_idle_conns=4

mysql:
  url: mysql://tcp(a)/b?parseTime=true&multiStatements=true

cockroach:
  url: crdb://a/b
